### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by igorsantos07** [guzzle/guzzle-services#143] opened 2017-05-07 06:01 UTC
I was interested in implementing an API Client using Guzzle Services, but got a bit lost reading the simple README file. There's no description of the options, allowed types and whatnot... Nor a documentation link.

I found an [old doc from Guzzle 3](http://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#), though. Is this still valid? If yes, shouldn't it be linked in the readme/repository URL? If no... is it possible to update something like that so people can refer to whenever using this repo? Such config-based project must have a documentation attached :P

**Comment by MI-LA01** [comment] 2017-05-10 21:10
+1

**Comment by pwaterz** [comment] 2017-05-23 21:02
Is this project being actively maintained? I too am wondering the same thing.

**Comment by pwaterz** [comment] 2017-05-23 21:13
Looking through the test https://github.com/guzzle/guzzle-services/blob/master/tests/DescriptionTest.php, it looks like the options are the same for guzzle 6

**Comment by Konafets** [comment] 2017-05-23 21:43
Hi, 

the project working as in the old documentation described. I like to extract the part from the old doc but need to find the time. Its on my todo list :-)

**Comment by shadowhand** [comment] 2017-07-06 17:35
I would love to see the old docs added to the README or something. It took me quite a while to realize the old docs were still relevant.

**Comment by GrahamCampbell** [comment] 2022-03-03 11:26
Duplicate of https://github.com/guzzle/guzzle-services/issues/69.

**Closed by GrahamCampbell** 2022-03-03 11:26 UTC
