### ISSUE TITLE
Map a json-array into a Model

### ISSUE THREAD

**Issue by matks** [guzzle/guzzle-services#80] opened 2015-03-18 13:05 UTC
Hello,

I am trying to find a way to map a json-array to an array of Model with a json service description.

The json returned by the API is quite simple:

```
[
    {
        "id": "2017335",
        "name": "A"
    },
    {
        "id": "2017338",
        "name": "B"
    },
    {
        "id": "20173357",
        "name": "C"
    }
]
```
 but although I have tried a lot of different ways, such as:

```
    "models": {
        "getMultipleOutput": {
            "type": "object",
            "additionalProperties": {
                "location": "json",
                "$ref": "SimpleOutput"
            }
        },
        "SimpleOutput": {
            "type": "object",
            "properties": {
                "id": {
                    "location": "json",
                    "type": "integer"
                },
                "name": {
                    "location": "json",
                    "type": "string"
                }
            }
        }
    }
```

```
    "models": {
        "getMultipleOutput": {
            "type": "object",
            "additionalProperties": {
                "location": "json",
                "type": "object",
                "properties": {
                    "id": {
                        "location": "json",
                        "type": "integer"
                    },
                    "name": {
                        "location": "json",
                        "type": "string"
                    }
                }
            }
        }
    }
``` 
```
    "models": {
        "getMultipleOutput": {
            "type": "object",
            "location": "json",
            "additionalProperties": {
                "location": "json",
                "type": "object",
                "properties": {
                    "id": {
                        "location": "json",
                        "type": "integer"
                    },
                    "name": {
                        "location": "json",
                        "type": "string"
                    }
                }
            }
        }
    }
``` 

and also
```
    "models": {
        "getMultipleOutput": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "location": "json",
                        "type": "integer"
                    },
                    "name": {
                        "location": "json",
                        "type": "string"
                    }
                }
            }
        }
    }
```

None of this works, some will return an empty array, other a GuzzleHttp\Exception\ParseException: `Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON`.

Could you tell me if this is possible with guzzle-services ?

Thank you very much in advance for any hint !

**Comment by hassankhan** [comment] 2015-03-19 16:05
I was pointed to this: https://github.com/Rarst/wporg-client/blob/33fb0dcce9f170b92824d09f5717ca814d7ecd29/php/WporgService.php and it worked for me :)

**Comment by wirtsi** [comment] 2015-04-23 14:28
Still, I don't see why the first approach should not work. I mean clearly the outer structure should be marked as an array, but then this array consists of the given models.

This maybeToArray seems like a very odd solution to me...

**Comment by hassankhan** [comment] 2015-04-23 14:30
I know, but in the absence of any decent documentation this was the only solution I could find. If you could find a better solution, I would love to see it :smile:

**Comment by wirtsi** [comment] 2015-04-23 14:49
Hey ... just figured it out. You need to use "location" => "json" on the array definition. So for my use case this works
```
$description = new Description([
    'baseUrl' => 'http://localhost',
    'operations' => [
        'facets' => [
            'httpMethod' => 'GET',
            'uri' => 'fakeapi/facets.json',
            'responseModel' => 'Facets',
        ],
        'facet' => [
            'httpMethod' => 'GET',
            'uri' => 'fakeapi/facet.json',
            'responseModel' => 'Facet'
        ]
    ],
    'models' => [
        "Facet" => [
            "type" => "object",
            "properties" => [
                "id" => [
                    "location" => "json",
                    "type" => "int"
                ],
                "group_name" => [
                    "location" => "json",
                    "type" => "string"
                ],
                "name" => [
                    "location" => "json",
                    "type" => "string"
                ],
                "facet_id" => [
                    "location" => "json",
                    "type" => "int"
                ],
            ]
        ],
        'Facets' => [
            "type" => "array",
            "location" => "json",
            "items" => [
                "type" => "object",
                '$ref' => "Facet"
            ]
        ]
    ]
]);
$guzzle = new GuzzleClient($client, $description);

$command = $guzzle->getCommand('facets');

$result = $guzzle->execute($command);
```
Data in facet.json is
```
{
  "id": 257,
  "group_name": "material",
  "name": "Foo",
  "value": "Bar",
  "facet_id": 3606
}
```
and facets.json is an array of these

**Comment by matks** [comment] 2015-04-26 14:42
I did not succeed to use the maybeToArray function suggested by @hassankhan but @wirtsi answer did work for my case. Thanks !

**Comment by Konafets** [comment] 2016-10-20 09:16
I close the issue because it seems to be solved. Please reopen the issue if you have any further questions or the the issue is not solved in your opinion.

**Closed by Konafets** 2016-10-20 09:16 UTC
